import { Router } from 'express'
import { authenticate } from '../middleware/auth.js'
import { secureUpload } from '../middleware/upload.js'
import { profileImageUpload, videoUpload } from '../middleware/upload.js'
import { uploadBuffer } from '../services/mediaService.js'
import User from '../models/User.js'
import MediaAsset from '../models/MediaAsset.js'

const router = Router()
router.post('/documents', authenticate, secureUpload.array('documents', 5), async (req, res, next) => { try { const files = await Promise.all((req.files || []).map(async (file) => { const result = await uploadBuffer(file, { folder: 'northbridge/documents', resourceType: 'raw' }); const asset = await MediaAsset.create({ owner: req.user.sub, kind: 'document', publicId: result.public_id, url: result.url, secureUrl: result.secure_url, resourceType: result.resource_type, format: result.format, bytes: result.bytes, originalName: file.originalname }); return { id: asset.id, url: asset.secureUrl, mimeType: file.mimetype, size: file.size } })); res.status(201).json({ success: true, message: 'Documents uploaded securely', data: { files } }) } catch (error) { next(error) } })
router.post('/profile-image', authenticate, profileImageUpload.single('image'), async (req, res, next) => { try { if (!req.file) return res.status(422).json({ success: false, message: 'Profile image is required', errors: [] }); const result = await uploadBuffer(req.file, { folder: 'northbridge/profiles', resourceType: 'image' }); const previous = await User.findById(req.user.sub).select('profileImagePublicId').lean(); await User.findByIdAndUpdate(req.user.sub, { profileImageUrl: result.secure_url, profileImagePublicId: result.public_id }); if (previous?.profileImagePublicId) { /* old assets can be removed by a cleanup job */ } res.status(201).json({ success: true, message: 'Profile image uploaded successfully', data: { url: result.secure_url, publicId: result.public_id } }) } catch (error) { next(error) } })
router.post('/video', authenticate, videoUpload.single('video'), async (req, res, next) => { try { if (!req.file) return res.status(422).json({ success: false, message: 'Video is required', errors: [] }); const result = await uploadBuffer(req.file, { folder: 'northbridge/videos', resourceType: 'video' }); const asset = await MediaAsset.create({ owner: req.user.sub, kind: 'video', publicId: result.public_id, url: result.url, secureUrl: result.secure_url, resourceType: result.resource_type, format: result.format, bytes: result.bytes, duration: result.duration, originalName: req.file.originalname }); res.status(201).json({ success: true, message: 'Video uploaded successfully', data: { id: asset.id, url: asset.secureUrl, publicId: asset.publicId, duration: asset.duration } }) } catch (error) { next(error) } })
export default router
