import { ArrowRight, Check, X } from 'lucide-react'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { api } from '../api/client'

type Values = { name: string; email: string; phone?: string; subject?: string; message: string }
export function ContactForm({ onClose }: { onClose: () => void }) {
  const [sent, setSent] = useState(false)
  const [error, setError] = useState('')
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<Values>()
  const submit = async (values: Values) => { setError(''); try { await api.post('/v1/contact', values); setSent(true) } catch (requestError: any) { setError(requestError.response?.data?.message || 'Unable to send your message right now.') } }
  return <div className="fixed inset-0 z-30 grid place-items-center bg-[#192a24]/75 p-5"><section className="w-full max-w-lg bg-paper p-7 text-ink shadow-2xl" role="dialog" aria-modal="true" aria-labelledby="contact-title"><div className="mb-7 flex items-start justify-between"><div><p className="text-[10px] uppercase tracking-[.15em] text-forest">Contact Northbridge</p><h2 id="contact-title" className="mt-2 font-display text-4xl">Let’s talk.</h2></div><button className="p-2" aria-label="Close contact form" onClick={onClose}><X size={19} /></button></div>{sent ? <div className="py-8 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-[#e5e9dd] text-forest"><Check size={20} /></div><h3 className="mt-5 font-display text-3xl">Message received.</h3><p className="mt-2 text-sm text-[#69736c]">Our school office will be in touch shortly.</p></div> : <form className="space-y-4" onSubmit={handleSubmit(submit)}><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm">Name<input className="mt-2 w-full border border-[#d8d9d0] bg-transparent px-3 py-3 outline-none focus:border-forest" {...register('name', { required: 'Name is required' })} />{errors.name && <span className="text-xs text-red-700">{errors.name.message}</span>}</label><label className="block text-sm">Email<input className="mt-2 w-full border border-[#d8d9d0] bg-transparent px-3 py-3 outline-none focus:border-forest" type="email" {...register('email', { required: 'Email is required' })} />{errors.email && <span className="text-xs text-red-700">{errors.email.message}</span>}</label></div><label className="block text-sm">Subject<input className="mt-2 w-full border border-[#d8d9d0] bg-transparent px-3 py-3 outline-none focus:border-forest" {...register('subject')} /></label><label className="block text-sm">Message<textarea className="mt-2 min-h-28 w-full resize-y border border-[#d8d9d0] bg-transparent px-3 py-3 outline-none focus:border-forest" {...register('message', { required: 'Message is required', minLength: { value: 10, message: 'Message must be at least 10 characters' } })} />{errors.message && <span className="text-xs text-red-700">{errors.message.message}</span>}</label>{error && <p className="text-sm text-red-700">{error}</p>}<button className="flex w-full items-center justify-between bg-forest px-4 py-4 text-xs uppercase tracking-[.08em] text-white disabled:opacity-60" disabled={isSubmitting} type="submit">{isSubmitting ? 'Sending...' : 'Send message'} <ArrowRight size={16} /></button></form>}</section></div>
}
